# Generated by Django 3.1.7 on 2021-03-10 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waste_category',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='waste_image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='waste_image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='waste_image')),
                ('waste_status', models.CharField(choices=[('not-working', 'Not Working'), ('working', 'Working'), ('good', 'Good')], default='working', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location_lat', models.BigIntegerField()),
                ('location_long', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wastecategory')),
            ],
        ),
    ]
