# Generated by Django 3.1.7 on 2021-03-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_waste_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='location_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waste',
            name='location_long',
            field=models.FloatField(),
        ),
    ]
