# Generated by Django 3.1.7 on 2021-03-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210321_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='geom',
        ),
    ]
