# Generated by Django 3.1.7 on 2021-03-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210323_0805'),
        ('product', '0004_remove_waste_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sold', 'Item Sold'), ('canceled', 'Item Canceled'), ('req', 'Requested')], max_length=10)),
                ('seen', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientuser')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vendor')),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.waste')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created',),
            },
        ),
    ]
