# Generated by Django 3.1.7 on 2021-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
