# Generated by Django 3.1.7 on 2021-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_waste_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catg_img'),
        ),
    ]
