# Generated by Django 3.1.7 on 2021-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210401_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='status',
            field=models.CharField(choices=[('dr', 'Draft'), ('pd', 'Published')], default='dr', max_length=3),
        ),
    ]
