# Generated by Django 3.1.7 on 2021-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
