# Generated by Django 3.1.7 on 2021-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210323_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='registration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_certificate'),
        ),
    ]
