"""
Django settings for ewmis project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o#c=xq&i@1_&ebq_)dsx$v@qlopx7slso=b==%w!!g#x*4o^g1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'crispy_forms',
    'django_email_verification',
    'user',
    'vendor',
    'product',
    'client',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ewmis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context.notification_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'ewmis.wsgi.application'

SITE_ID = 1

# Auth User Model
AUTH_USER_MODEL = 'user.User'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'ishworewaste2',
        'USER': 'postgres',
        'PASSWORD': 'password',
        'HOST' : '127.0.0.1',
        'PORT' : 5432
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'

LOGOUT_REDIRECT_URL = "/"
# # https://docs.djangoproject.com/en/dev/ref/settings/#login-url
LOGIN_URL = "login"
# Message Framework Config
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'msg-error',
    messages.SUCCESS: 'msg-success',
    messages.INFO: 'msg-info',
    messages.WARNING: 'msg-warning',
}


def verified_callback(user):
    user.is_active = True


EMAIL_VERIFIED_CALLBACK = verified_callback
EMAIL_FROM_ADDRESS = 'noreply@ewastemandu.com'
EMAIL_MAIL_SUBJECT = 'Confirm your Account'
EMAIL_MAIL_HTML = 'mail_body.html'
EMAIL_MAIL_PLAIN = 'mail_body.txt'
EMAIL_TOKEN_LIFE = 60 * 60
EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
EMAIL_PAGE_DOMAIN = 'http://127.0.0.1:8000/'

# For Django Email Backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# FROM_EMAIL = 'noreply@ewastemandu.com'
# EMAIL_HOST_USER = '**@**.com'
# EMAIL_HOST_PASSWORD = '***'  # os.environ['password_key'] suggested
# EMAIL_USE_TLS = True
###################################
# EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
# FROM_EMAIL = 'noreply@ewastemandu.com'
# SENDGRID_API_KEY = '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'
# SENDGRID_SANDBOX_MODE_IN_DEBUG=False
# SENDGRID_ECHO_TO_STDOUT=True

import os
os.environ['GDAL_DATA'] = r"C:\Users\iacha\Desktop\project\venv\Lib\site-packages\osgeo\data\gdal"
os.environ['PROJ_LIB'] = r"C:\Users\iacha\Desktop\project\venv\Lib\site-packages\osgeo\data\proj"
os.environ['PATH'] = r"C:\Users\iacha\Desktop\project\venv\Lib\site-packages\osgeo" +";" + os.environ['PATH']
GDAL_LIBRARY_PATH = r'C:\Users\iacha\Desktop\project\venv\Lib\site-packages\osgeo\gdal302.dll'
